# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Mothership
# Description of the Site
description: A customizable Jekyll portfolio theme
# URL of Image of the Site
site-image: https://drive.google.com/file/d/1BZdBaMDRDm8yC40K4tJBY_MtlfX67LPD/view?usp=sharing
# Keywords of the Site
site-keywords: DAO, Community, NFT
# URL for the Image of custom Favicon
favicon-url: https://drive.google.com/file/d/1c8TLDrqd9XBuB0XA06MplVE2wxRXsmK4/view?usp=sharing

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://drive.google.com/file/d/1raEguEmTI4XKPvpgF-OpoHvtzA6GVQzR/view?usp=sharing
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: social@mothership.llc
facebook_username: mothershipDAO
twitter_username: mothershipDAO
instagram_username: mothershipDAO
linkedin_username: mothershipDAO
github_username:  mothershipDAO
youtube_channel_id: mothershipDAO
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: mothershipDAO

# Name of the Author
author-name: Mothership DAO
# URL for the Image of the Author
author-image: https://drive.google.com/file/d/1XKQcttUmRpsbBBPfyrOWEGTbOzMSyUvp/view?usp=sharing
# 60 Words About the Author
author-about: Mothership is devoted to using metaverse technology to making life better in the meatspace.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://mothership.llc

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
