# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Mothership DAO
# Description of the Site
description: A stake in a sustainable future
# URL of Image of the Site
site-image: /mothership-dao/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Mothership, DAO
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://gateway.pinata.cloud/ipfs/Qman9SvkbugLi99AVpRgjBKNoaKBqmmkv7q8UKpLXaLULb
# If you don't want to use any icon, you can leave them blank.
email: 
facebook_username: 
twitter_username: mothershipDAO
instagram_username: 
linkedin_username: 
github_username:  mothership-DAO
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Mothership DAO
# URL for the Image of the Author
author-image: https://gateway.pinata.cloud/ipfs/QmNRukqMbbBgGbFZgs1QDfw7w5x8uiP722GJt6TXxi2oXR/meta.jpg
# 60 Words About the Author
author-about: Mothership DAO is dedicated to providing safe, productive spaces for community members to grow and prosper, using a user-centric, privacy-by-design approach. Mothership supports artists, musicians and other creative talent as they fly in the metaverse and live in the meatspace.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: "https://discord.gg/G7xpDgut"
# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
